// <auto-generated />
using LanguageTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LanguageTracker.Migrations
{
    [DbContext(typeof(LanguageTrackerContext))]
    [Migration("20190514152357_Instructors")]
    partial class Instructors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LanguageTracker.Controllers.Instructors", b =>
                {
                    b.Property<int>("id");

                    b.Property<string>("first_name");

                    b.Property<string>("last_name");

                    b.HasKey("id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("LanguageTracker.Controllers.Students", b =>
                {
                    b.Property<int>("sid");

                    b.Property<string>("first_name");

                    b.Property<string>("last_name");

                    b.HasKey("sid");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
